context:
    dynamo_home: '/Users/chmu/tmp/dynamo-home'
    frameworks: ["Cocoa", "OpenGL", "OpenAL", "AGL", "IOKit", "Carbon", "CoreVideo", "Foundation", "AppKit", "Carbon"]

exportedSymbols: []
main: |
    #include <stdio.h>

    {{#symbols}}
    extern "C" void {{.}}();
    {{/symbols}}

    void dmExportedSymbols() {
        {{#symbols}}
        {{.}}();
        {{/symbols}}
    }

    extern "C" void Test();
    int main(int argc, char *argv[])
    {
        printf("Hello Extender\n");
        Test();
        return 0;
    }

includes: ['{{dynamo_home}}/include', '{{dynamo_home}}/ext/include']
platforms:
  x86-osx:
    context:
        engineLibs: []
    exeExt: ''
    shlibExt: '.dylib'
    shlibRe: 'lib(.+).dylib'
    stlibRe: 'lib(.+).a'
    compileCmd: 'clang++ -c -m32 {{#includes}}-I{{.}} {{/includes}} {{src}} -o{{tgt}}'
    linkCmd: clang++ -m32 -stdlib=libstdc++ {{#src}}{{.}} {{/src}} -o {{tgt}} {{#libPaths}}-L{{.}} {{/libPaths}} {{#extLibs}}{{.}} {{/extLibs}} {{#libs}}-l{{.}} {{/libs}}
    libCmd: 'ar rcs {{tgt}} {{#objs}}{{.}} {{/objs}}'
